services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - PORT=${PORT}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - VITE_BACKEND_ORIGIN=${VITE_BACKEND_ORIGIN}
